[[ER_Overview]]
== Summary of Testbed 15 Engineering Reports

A set of OGC Engineering Reports (ERs) describe the various activities completed as part of the Testbed 15 initiative. Each ER provides an Executive Summary followed by documentation on the research approach and technical details of the prototype implementations. The ER concludes with a summary of the results, recommendations related to the current OGC Standards baseline, and recommendations for future interoperability initiative work.

OGC Engineering Reports have been presented to the OGC Membership at an OGC Technical Committee meeting. The Members then vote to approve each ER for public release.

Following is the complete set of Testbed 15 ERs:

[options="header"]
|===
|OGC Doc #|TB 15 Task|Title 
|19-021  | D001| http://docs.opengeospatial.org/per/19-021.html[Semantic Web Link Builder and Triple Generator Engineering Report]
|19-027r2| D002| http://docs.opengeospatial.org/per/19-027r2.html[Machine Learning Engineering Report]
|19-016r1| D004| http://docs.opengeospatial.org/per/19-016r1.html[Data Centric Security Engineering Report]
|19-012r1| D005| http://docs.opengeospatial.org/per/19-012r1.html[Delta Updates Engineering Report]
|19-020r1| D010| http://docs.opengeospatial.org/per/19-020r1.html[Catalogue and Discovery Engineering Report]
|19-023r1| D011| http://docs.opengeospatial.org/per/19-023r1.html[Encoding and Metadata Conceptual Model for Styles Engineering Report]
|19-010r2| D012| http://docs.opengeospatial.org/per/19-010r2.html[Styles API Engineering Report]
|19-069  | <<D014>>| http://docs.opengeospatial.org/per/19-069.html[Maps and Tiles API Engineering Report]
|19-018  | D015| http://docs.opengeospatial.org/per/19-018.html[Open Portrayal Framework Engineering Report]
|19-019  | D017| http://docs.opengeospatial.org/per/19-019.html[Portrayal Summary Engineering Report]
|19-024  | D019| http://docs.opengeospatial.org/per/19-024r1.html[Federated Clouds Security Engineering Report]
|19-026  | D020| http://docs.opengeospatial.org/per/19-026.html[Federated Clouds Analytics Engineering Report]
|10-022r1| D021| http://docs.opengeospatial.org/per/19-022r1.html[Scaling Units of Work (EOC, Scale, SEED) Engineering Report]
|19-015  | D022| http://docs.opengeospatial.org/per/19-015.html[Federated Cloud Provenance Engineering Report]
|19-023  | D023| http://docs.opengeospatial.org/per/19-046r1.html[Quebec Model MapML Engineering Report]
|===

Every OGC Engineering Report (ER) has an official OGC document number. This is for easy reference. "TB 15 Task" refers to the internal task number used in the Testbed and are used as easy references in the Call for Participation and all documents and presentation materials developed in the Testbed. If you click on the Testbed task number, you will be redirected to a short summary of that particular ER.

OGC ERs may be copied, distributed, and used as required for research and related activities. ERs, however, are _not_ official positions of the OGC Membership and should never be listed as mandatory requirements in procurements. 

=== ER Summaries

[[D014]]
==== D014

*Testbed 15 Maps and Tiles API Engineering Report*

Since 2017, the OGC has had focused effort developing API standards that support the Resource Oriented Architecture and are described using the https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md[OpenAPI 3.0] specification. The ER defines a proof-of-concept for a maps and tiles API specification.

The draft Maps and Tiles specification builds on the OGC API - Features - Part 1: Core standard. The draft Tiles specification describes a service that retrieves data representations as tiles. In the draft specification, the assumption is that tiles are organized into https://www.opengeospatial.org/standards/tms[Tile Matrix Sets (TMS)] consisting of regular tile matrices available at different scales or resolutions.

The draft Maps specification describes an API that presents data as maps by applying a style. These maps can be retrieved in a tiled structure or as maps of any size generated on-the-fly. Some of the functionality in the draft Maps specification is based on the https://www.opengeospatial.org/standards/wmts[OGC Web Map Tile Service (WMTS) 1.0] standard. This is related to the use of styles by using the draft Styles API specification that was developed in the Testbed-15 Open Portrayal Framework thread.
