[[ER_Overview]]
== Summary of Testbed 15 Engineering Reports

A set of OGC Engineering Reports (ERs) describe the various activities completed as part of the Testbed 15 initiative. Each ER provides an Executive Summary followed by documentation on the research approach and technical details of the prototype implementations. The ER concludes with a summary of the results, recommendations related to the current OGC Standards baseline, and recommendations for future interoperability initiative work.

OGC Engineering Reports have been presented to the OGC Membership at an OGC Technical Committee meeting. The Members then vote to approve each ER for public release.

Following is the complete set of Testbed 15 ERs:

[options="header"]
|===
|OGC Doc #|TB 15 Task|Title 
|19-021  | D001| http://docs.opengeospatial.org/per/19-021.html[Semantic Web Link Builder and Triple Generator Engineering Report]
|19-027r2| <<D002,D002>>| http://docs.opengeospatial.org/per/19-027r2.html[Machine Learning Engineering Report]
|19-016r1| D004| http://docs.opengeospatial.org/per/19-016r1.html[Data Centric Security Engineering Report]
|19-012r1| D005| http://docs.opengeospatial.org/per/19-012r1.html[Delta Updates Engineering Report]
|19-020r1| D010| http://docs.opengeospatial.org/per/19-020r1.html[Catalogue and Discovery Engineering Report]
|19-023r1| D011| http://docs.opengeospatial.org/per/19-023r1.html[Encoding and Metadata Conceptual Model for Styles Engineering Report]
|19-010r2| D012| http://docs.opengeospatial.org/per/19-010r2.html[Styles API Engineering Report]
|19-069  | <<D014,D014>>| http://docs.opengeospatial.org/per/19-069.html[Maps and Tiles API Engineering Report]
|19-018  | D015| http://docs.opengeospatial.org/per/19-018.html[Open Portrayal Framework Engineering Report]
|19-070  | <<D016,D016>>|  http://docs.opengeospatial.org/per/19-070.html[Images and ChangesSet API Engineering Report]
|19-019  | D017| http://docs.opengeospatial.org/per/19-019.html[Portrayal Summary Engineering Report]
|19-024r1| <<D019,D019>>| http://docs.opengeospatial.org/per/19-024r1.html[Federated Clouds Security Engineering Report]
|19-026  | D020| http://docs.opengeospatial.org/per/19-026.html[Federated Clouds Analytics Engineering Report]
|10-022r1| <<D021,D021>>| http://docs.opengeospatial.org/per/19-022r1.html[Scaling Units of Work (EOC, Scale, SEED) Engineering Report]
|19-015  | D022| http://docs.opengeospatial.org/per/19-015.html[Federated Cloud Provenance Engineering Report]
|19-023  | <<D023,D023>>| http://docs.opengeospatial.org/per/19-046r1.html[Quebec Model MapML Engineering Report]
|===

Every OGC Engineering Report (ER) has an official OGC document number. This is for easy reference. "TB 15 Task" refers to the internal task number used in the Testbed and are used as easy references in the Call for Participation and all documents and presentation materials developed in the Testbed. If you click on the Testbed task number, you will be redirected to a short summary of that particular ER.

OGC ERs may be copied, distributed, and used as required for research and related activities. ERs, however, are _not_ official positions of the OGC Membership and should never be listed as mandatory requirements in procurements. 

=== ER Summaries

[[D002]]

==== D002: Machine Learning Engineering Report

The Machine Learning (ML) ER documents the results of the Testbed 15 ML thread . Participants explored the ability of ML to interact with and use OGC web standards in the context of natural resources applications. As such, a key purpose of the research was to demonstrate the use of OGC standards in the ML domain through scenario development. The scenarios used in the ML thread were:

* Petawawa Super Site Research forest change prediction model.
* New Brunswick forest supply management decision maker ML models.
* Quebec Lake river differentiation ML models.
* Richelieu River Hydro linked data harvest models.
* Arctic web services discovery ML model.

Each scenario utilized a set of supporting geospatial data coupled with cataloging and processing services to support the research objectives. A ML model is at the core of each scenario. In each scenario the goal was to have the model make key decisions that a human in the system would typically make under normal circumstances. Each scenario and corresponding prototype implementations were supported by at least one client to demonstrate the execution and parsing of outputs for visualization.

In summary, the ML thread included five scenarios utilizing seven ML models in a solution architecture that included implementations of the OGC Web Processing Service (WPS), OGC Web Feature Service (WFS) and OGC Catalogue Service for the Web (CSW) standards. This ER includes a thorough investigation and documentation of the experiences of the thread participants resulting in a set of recommendations for future work.

[[D014]]

==== D014: Testbed 15 Maps and Tiles API Engineering Report

Since 2017, the OGC has had a focused effort developing API standards based on the concepts defined in a Resource Oriented Architecture (ROA) The OGC APIs are described using the https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md[OpenAPI 3.0] specification. The ER defines a proof-of-concept for a maps and tiles API specification.

The draft Maps and Tiles specification builds on the OGC API - Features - Part 1: Core standard. The draft Tiles specification describes a service that retrieves data representations as tiles. In the draft specification, the assumption is that tiles are organized into https://www.opengeospatial.org/standards/tms[Tile Matrix Sets (TMS)] consisting of regular tile matrices available at different scales or resolutions.

The draft Maps specification describes an API that presents data as maps by applying a style. These maps can be retrieved in a tiled structure or as maps of any size generated on-the-fly. Some of the functionality in the draft Maps specification is based on the https://www.opengeospatial.org/standards/wmts[OGC Web Map Tile Service (WMTS) 1.0] standard. This is related to the use of styles by using the draft Styles API specification that was developed in the Testbed-15 Open Portrayal Framework thread.

[[D016]]

==== D016: Images and ChangesSet API Engineering Report

The Images and ChangesSet API ER define two related draft specifications that address the use case of a tile server that serves tiled images and a client that portrays the result as a set of images. A backend tile server provides access to a set of tiled images, such as satellite scenes or pictures captured using a drone. Access is via a standard API interface. The source images should be able to be updated. Therefore the tile server also needs to be able to deliver only those tiles that have changed.

The draft API specification is divided into two independent but related APIs . The OGC API – Images: Enables managing (retrieving, creating and updating) sets of images that are georeferenced. The API enables the mosaicking use case (where the imagery is combined in a single bigger “picture”) but could also serve for a use case in which a moving camera is taking pictures at locations along a route and then stores the images as a single collection. The draft Changeset Filter API enables filtering a request to a data service that specifies rules such that only recent changes are delivered to the client.

[[D019]]

==== D019: Federated Clouds Security Engineering Report

The Federated Clouds Security ER documents the analysis of two types of federation: The centralized entity and distributed architecture approaches. Both approaches were analyzed through the lens of security. The work documented in this ER is on analyzing how federated membership, resource and access policy management can be provided within a security environment, while also providing portability and interoperability to all stakeholders. The work presented in the ER also took into account how governance can be affected by design choices. The ER also provides an introduction to the concepts of Federation and Federated Clouds and then introduces the concept of a Federation Manager (FM) and tries to establish a clear list of functionality aspects necessary to manage and use a Federation. The ER concludes with a complete analysis of the Federation Managers deployed during this Testbed-15 activity, and how to tackle each of the functionality challenges.

[[D021]]

==== D021: Scaling Units of Work (EOC, Scale, SEED) Engineering Report
This ER presents a thorough analysis of the work produced in the Earth Observation Clouds (EOC) threads in OGC Testbeds 13 and 14 in relation to the US National Geospatial Intelligence (NGA) GeoInt https://github.com/ngageoint/scale[Scale] and https://github.com/ngageoint/seed[SEED] environments. Scale provides management of automated processing on a cluster of machines. The SEED specification aids the discovery and consumption of a discrete unit of work contained within a Docker image. The ER attempts to explain how the OGC Testbed-13 and OGC Testbed-14 research results of "bringing applications/users to the data" relate to Scale and SEED. While comparing the two approaches, the ER identifies and describes opportunities for harmonization or standardization. This includes features that must remain separate and why. These hard problems require additional work. For developers, the ER constitutes a technical reference supporting the comparison of the two approaches, thereby enabling developers to make informed choices, understand trade-offs, identify relevant standards and clarify misunderstandings.

[[D023]]

==== D023: Quebec Model MapML Engineering Report

The Quebec Model MapML ER describes the Map Markup Language (MapML) enabled client implementation for the Quebec Lake-River Differentiation Model in the Machine Learning (ML) task. This ER describes the MapML parsing capabilities that were developed to illustrate the outputs of a ML model to delineate lake and river features from an undifferentiated waterbody vector dataset in Québec, Canada. Client data was accessed through an OGC Web Processing Service (WPS) interface in coordination with an OGC API - Features implementation.
