[[thread-summaries]]

== Thread Summaries

The following are overviews of each of the major Testbed 15 thread activities.

[[SFC]]

=== Thread 1: Secure Data and Federated Clouds (SFC)

==== Data Centric Security

*Explore How Data Centric Security principals can be applied at the feature level in a geospatial data store.*

Data-centric security is an approach to security that emphasizes the security of the data itself rather than the security of networks, servers, or applications. In Testbed-15, the focus was on how security works at a Feature Level as well as implications as a data burden on the network. With focus on the actual interactions and general workflows, Testbed-15 work sought to answer the question of how data centric security can be applied to OGC standards based architectures:

* How does data centric security works with OGC standards and best practices?
* Which elements are already supported and how?
* Which modifications to existing standards or best practices are necessary to exploit full potential of data centric security?

To answer those questions, the particpants examined the use of encrypted containers in combination with geospatial data using the encoding for an OGC API for Features and the Web Feature Service (WFS) FeatureCollection structure. Within that context, the particants looked at the use of encrypted container formats such as NATO STANAG 4778 "Information on standard Metadata Binding" with metadata as defined in NATO STANAG 4774 "Confidentiality Metadata Label Syntax" to permit the sharing of sensitive information between allies.

==== Federated Cloud Analytics

[[CPP]]

=== Thread 2: Cloud Processing and Portrayal (CPP)

==== Earth Observation Process and Application Discovery

==== Open Portrayal Framework

[[MLD]]

=== Thread 3: Machine Learning and Delta Updates (MLD)

==== Machine Learning

==== Delta Updates

