[[thread-summaries]]

== Thread Summaries

The following are overviews of each of the major Testbed 15 thread activities.

[[SFC]]

=== Thread 1: Secure Data and Federated Clouds (SFC)

==== Data Centric Security

*Explore How Data Centric Security principals can be applied at the feature level in a geospatial data store.*

Data-centric security is an approach to security that emphasizes the security of the data itself rather than the security of networks, servers, or applications. In Testbed-15, the focus was on how security works at a Feature Level as well as implications as a data burden on the network. With focus on the actual interactions and general workflows, Testbed-15 work sought to answer the question of how data centric security can be applied to OGC standards based architectures:

* How does data centric security works with OGC standards and best practices?
* Which elements are already supported and how?
* Which modifications to existing standards or best practices are necessary to exploit full potential of data centric security?

To answer those questions, the particpants examined the use of encrypted containers in combination with geospatial data using the encoding for an OGC API for Features and the Web Feature Service (WFS) FeatureCollection structure. Within that context, the particants looked at the use of encrypted container formats such as NATO STANAG 4778 "Information on standard Metadata Binding" with metadata as defined in NATO STANAG 4774 "Confidentiality Metadata Label Syntax" to permit the sharing of sensitive information between allies.

In general, the work performed in Testbed 15 was able to demonstrate that with a security proxy and an OGC API - Features service, an implementation can satisfy the requirements for a data centric security model. The Engineering Report documents the results of implementing three scenarios. Scenarios one and two show a backward compatible method for implementing data centric security. One requirement that was not completely investigated in the first two scenarios was encryption of the data from the author to storage. 

The following are additional information resources regarding the Data Centric Security task.

[options="header"]
|===
| Information Resource | Location of resource
| Engineering Report(s) |http://docs.opengeospatial.org/per/19-016r1.html[Data Centric Security Engineering Report]
| Power Point Presentation | link:https://github.com/cnreediii/testbed15-summary/blob/master/slides/Testbed%2015%20Data%20Centric%20Security.pdf[Slide presentation]
| Short Video | link:https://www.youtube.com/watch?v=5_ynVa8ZMY4&list=PLQsQNjNIDU85HBDZWc8aE7EvQKE5nIedK&index=7&t=0s[Youtube Video]
|===

==== Federated Cloud Analytics

[options="header"]
|===
| Information Resource | Location of resource
| Engineering Report(s) |http://docs.opengeospatial.org/per/19-016r1.html[Data Centric Security Engineering Report]
| Power Point Presentation | link:https://github.com/cnreediii/testbed15-summary/blob/master/slides/Testbed%2015%20Federated%20Cloud%20analytics.pdf[Slide presentation]
| Short Video | link:https://portal.opengeospatial.org/files/?artifact_id=91766[OGC Video]
|===

[[CPP]]

=== Thread 2: Cloud Processing and Portrayal (CPP)

==== Earth Observation Process and Application Discovery

==== Open Portrayal Framework

[[MLD]]

=== Thread 3: Machine Learning and Delta Updates (MLD)

==== Machine Learning

==== Delta Updates

